### PR TITLE
rejigger bit counting intrinsics

### LINKED ISSUE #867: Improve compression speed on ZEN/ZEN2
MSVC implementation of `LZ4_NbCommonBytes` compiles to `bsf` asm instruction, which is suboptimal on ZEN/ZEN2 uarchs, as indicated below (the code compiles to `R, R` variant):

obraz

Similar in behavior `tzcnt` instruction has better internal implementation:

obraz

Quoting Intel manuals:

> The key difference between TZCNT and BSF instruction is that TZCNT provides operand size as output when source operand is zero while in the case of BSF instruction, if source operand is zero, the content of destination operand are undefined.

This case can be ignored, as `LZ4_count` function will never pass zero as input parameter.

Technically `tzcnt` is a part of BMI1 instruction set, but this also doesn't matter:

> On processors that do not support TZCNT, the instruction byte encoding is executed as BSF.

On Intel uarchs I don't expect any performance difference, if instruction tables are to be believed.

On ZEN2 number of `LZ4_NbCommonBytes` profiling samples was reduced from 24% in the `bsf` case to 15% in `tzcnt` case.

For completness, here's result of running `fullbench` in a noisy environment:

Before:

```
*** LZ4 speed analyzer v1.9.2 64-bits, by Yann Collet ***
 dickens :
Compression functions :
 1-LZ4_compress_default               :  10192446 ->  6431106 (63.10%),  419.1 MB/s
 2-LZ4_compress_default(small dst)    :  10192446 ->  6431106 (63.10%),  415.5 MB/s
 3-LZ4_compress_destSize              :  10192446 ->  6431106 (63.10%),  382.0 MB/s
 4-LZ4_compress_fast(0)               :  10192446 ->  6431106 (63.10%),  417.9 MB/s
 5-LZ4_compress_fast(1)               :  10192446 ->  6431106 (63.10%),  413.2 MB/s
 6-LZ4_compress_fast(2)               :  10192446 ->  6763934 (66.36%),  453.4 MB/s
 7-LZ4_compress_fast(17)              :  10192446 ->  9222511 (90.48%), 1190.5 MB/s
 8-LZ4_compress_fast_extState(0)      :  10192446 ->  6431106 (63.10%),  415.0 MB/s
 9-LZ4_compress_fast_continue(0)      :  10192446 ->  6428753 (63.07%),  422.5 MB/s
10-LZ4_compress_HC                    :  10192446 ->  4441354 (43.57%),   23.0 MB/s
12-LZ4_compress_HC_extStateHC         :  10192446 ->  4441354 (43.57%),   22.9 MB/s
14-LZ4_compress_HC_continue           :  10192446 ->  4432831 (43.49%),   23.0 MB/s
20-LZ4_compress_forceDict             :  10192446 ->  6428753 (63.07%),  382.9 MB/s
30-LZ4F_compressFrame                 :  10192446 ->  6430041 (63.09%),  409.2 MB/s
 ooffice :
Compression functions :
 1-LZ4_compress_default               :   6152192 ->  4339312 (70.53%),  532.3 MB/s
 2-LZ4_compress_default(small dst)    :   6152192 ->  4339312 (70.53%),  524.3 MB/s
 3-LZ4_compress_destSize              :   6152192 ->  4339312 (70.53%),  516.0 MB/s
 4-LZ4_compress_fast(0)               :   6152192 ->  4339312 (70.53%),  546.8 MB/s
 5-LZ4_compress_fast(1)               :   6152192 ->  4339312 (70.53%),  553.5 MB/s
 6-LZ4_compress_fast(2)               :   6152192 ->  4552666 (74.00%),  684.4 MB/s
 7-LZ4_compress_fast(17)              :   6152192 ->  5531363 (89.91%), 1845.7 MB/s
 8-LZ4_compress_fast_extState(0)      :   6152192 ->  4339312 (70.53%),  554.4 MB/s
 9-LZ4_compress_fast_continue(0)      :   6152192 ->  4338923 (70.53%),  517.8 MB/s
10-LZ4_compress_HC                    :   6152192 ->  3546025 (57.64%),   40.4 MB/s
12-LZ4_compress_HC_extStateHC         :   6152192 ->  3546025 (57.64%),   39.8 MB/s
14-LZ4_compress_HC_continue           :   6152192 ->  3543767 (57.60%),   39.5 MB/s
20-LZ4_compress_forceDict             :   6152192 ->  4338923 (70.53%),  532.3 MB/s
30-LZ4F_compressFrame                 :   6152192 ->  4339971 (70.54%),  550.4 MB/s
```

After:

```
*** LZ4 speed analyzer v1.9.2 64-bits, by Yann Collet ***
 dickens :
Compression functions :
 1-LZ4_compress_default               :  10192446 ->  6431106 (63.10%),  426.0 MB/s
 2-LZ4_compress_default(small dst)    :  10192446 ->  6431106 (63.10%),  418.1 MB/s
 3-LZ4_compress_destSize              :  10192446 ->  6431106 (63.10%),  400.6 MB/s
 4-LZ4_compress_fast(0)               :  10192446 ->  6431106 (63.10%),  419.3 MB/s
 5-LZ4_compress_fast(1)               :  10192446 ->  6431106 (63.10%),  424.7 MB/s
 6-LZ4_compress_fast(2)               :  10192446 ->  6763934 (66.36%),  471.0 MB/s
 7-LZ4_compress_fast(17)              :  10192446 ->  9222511 (90.48%), 1226.7 MB/s
 8-LZ4_compress_fast_extState(0)      :  10192446 ->  6431106 (63.10%),  419.9 MB/s
 9-LZ4_compress_fast_continue(0)      :  10192446 ->  6428753 (63.07%),  441.6 MB/s
10-LZ4_compress_HC                    :  10192446 ->  4441354 (43.57%),   23.0 MB/s
12-LZ4_compress_HC_extStateHC         :  10192446 ->  4441354 (43.57%),   23.0 MB/s
14-LZ4_compress_HC_continue           :  10192446 ->  4432831 (43.49%),   22.8 MB/s
20-LZ4_compress_forceDict             :  10192446 ->  6428753 (63.07%),  406.9 MB/s
30-LZ4F_compressFrame                 :  10192446 ->  6430041 (63.09%),  420.1 MB/s
 ooffice :
Compression functions :
 1-LZ4_compress_default               :   6152192 ->  4339312 (70.53%),  535.2 MB/s
 2-LZ4_compress_default(small dst)    :   6152192 ->  4339312 (70.53%),  551.9 MB/s
 3-LZ4_compress_destSize              :   6152192 ->  4339312 (70.53%),  551.0 MB/s
 4-LZ4_compress_fast(0)               :   6152192 ->  4339312 (70.53%),  533.8 MB/s
 5-LZ4_compress_fast(1)               :   6152192 ->  4339312 (70.53%),  531.9 MB/s
 6-LZ4_compress_fast(2)               :   6152192 ->  4552666 (74.00%),  691.2 MB/s
 7-LZ4_compress_fast(17)              :   6152192 ->  5531363 (89.91%), 1886.7 MB/s
 8-LZ4_compress_fast_extState(0)      :   6152192 ->  4339312 (70.53%),  565.5 MB/s
 9-LZ4_compress_fast_continue(0)      :   6152192 ->  4338923 (70.53%),  544.8 MB/s
10-LZ4_compress_HC                    :   6152192 ->  3546025 (57.64%),   40.5 MB/s
12-LZ4_compress_HC_extStateHC         :   6152192 ->  3546025 (57.64%),   40.5 MB/s
14-LZ4_compress_HC_continue           :   6152192 ->  3543767 (57.60%),   40.4 MB/s
20-LZ4_compress_forceDict             :   6152192 ->  4338923 (70.53%),  534.5 MB/s
30-LZ4F_compressFrame                 :   6152192 ->  4339971 (70.54%),  552.2 MB/s
```

Proposed change: https://github.com/wolfpld/tracy/commit/3a302c18bcd1b7956890dbb5edba73a5db93017f

### PR DESCRIPTION
**Pull request by aqrit**
Fix lz4/lz4#867
Optimize software fallback routines.
Delete some faulty (and dead?) MSVC big endian code.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Could you publish some benchmark and/or profile results 
showing that the new software fallback is more efficient ?

**Comment by aqrit** [comment]
The new little endian fallback is unlikely to show up in any "fair" benchmark.
If we're against nonessential changes I can switch it back to the DeBruijn method.

Static analysis (https://godbolt.org/z/cYqxTW) shows the new proposed method to have lower latency.
It replaces the table lookup with a bitwise-and.

```
Clang -O3 -fPIC
    DeBruijn:
        Instructions:      8
        Total Cycles:      15
    HSum:
        Instructions:      7
        Total Cycles:      10

clang -O3 -march=skylake
    DeBruijn:
        Instructions:      5
        Total Cycles:      13
    HSum:
        Instructions:      6
        Total Cycles:      9
```
   
LLVM-MCA assigns a latency of 5 cycles to the table lookup. 
Even assigning 2 cycles for a table lookup does not make the DeBruijn method's latency better 
than the HSum method.

---

I have no clue how a typical big endian machine behaves.

The proposed 64-bit big endian method would be an "obvious" win, 
**if** the CPU has fast 64-bit multiplications and expensive branch misses.
 
The proposed 32-bit big endian method has good reciprocal throughput - when unrolled on x64 - but 
I am concerned about how it might perform in this instance.

**Comment by Cyan4973** [comment]
Analysis is fine.
Provided figures in instructions and cycle are a good enough start.

This could be completed with more dynamic measurements, with a tool like `perf`, though I understand that it's more difficult to do since this part of the algorithm is dwarfed by other concerns in the compression routine.

> The new little endian fallback is unlikely to show up in any "fair" benchmark.

This part of the code, counting bytes to extract the match length, is among the hottest ones.
I would have expected that forcing the algorithm to use the software fallback
should make it possible to notice a difference, even a small one.

If I do remember correctly, the difference between hardware vs software code paths for byte count was measurable.

Also, it would provide a way to ensure that the code is indeed correct.

> If we're against nonessential changes 

There is no such thing. If the benefit seems good enough, this code can be merged.
It's just that it wouldn't be the first time that a performance tweak that "seem fine" on paper ends up being strangely detrimental in practice. Hence, nothing can nor should replace direct measurements.

Also, sometimes, some of these "improvements" introduce other concerns, such as complexity, code size or portability limitations. 
The good news here is that your PR seems free of those concerns for the most part,
except maybe in one code path where it adds a 128-byte table where none was previously present.

**Comment by aqrit** [comment]
make CFLAGS=-DLZ4_FORCE_SW_BITCOUNT
sudo perf record ./lz4 -b1 silesia.tar out
sudo perf report

LZ4_NbCommonBytes
original: 0.83%
patch:    0.66%

**Comment by Cyan4973** [comment]
This looks good.
I believe it's a right direction,
at the very least for the little-endian software backup.

For the big-endian one,
I'm a bit interrogative about the code for 64-bit big-endian,
because it adds a substantial lookup table to the code (128 bytes).
I can imagine some push-back on this.

Hence I was wondering if an alternative using less table space would be achievable ?
It looks as if the table could be folded in some way, due to large repetitions within columns.

**Comment by aqrit** [comment]
Nothing good comes to mind.
There is no fast way to isolate the highest set bit or smear right.
In this case, the extracted bits get reversed (for no real reason) which turns it into a 7-bit count trailing zero problem.
Which could be solved in the usual ways (popcnt, DeBruijn, etc.) but that is a lot of extra instructions.

The table size could be halved at the cost of 3 instructions (1 on the critical path):
```
static const unsigned char ctz7_tab[64] = {
	7, 1, 2, 1, 3, 1, 2, 1, 4, 1, 2, 1, 3, 1, 2, 1,
	5, 1, 2, 1, 3, 1, 2, 1, 4, 1, 2, 1, 3, 1, 2, 1,
	6, 1, 2, 1, 3, 1, 2, 1, 4, 1, 2, 1, 3, 1, 2, 1,
	5, 1, 2, 1, 3, 1, 2, 1, 4, 1, 2, 1, 3, 1, 2, 1
};
const U64 mask = 0x0101010101010101ULL;
U64 t = (((val >> 8) - mask) | val) & mask;
return ctz7_tab[(t * 0x0080402010080402ULL) >> 58] & ((t >> 56) - 1);
```

**Comment by Cyan4973** [comment]
Integrating into a feature branch,
in order to adjust comments.

**Pull request merged**
