### PR TITLE
Added `BUNDLE	DESTINATION`

### PR DESCRIPTION
**Pull request by dooxe**
Added `BUNDLE	DESTINATION` to target `${LZ4_PROGRAMS_BUILT}` in the `CMakeLists.txt`.
Like that, it is compatible with newer versions of cmake (tested on 3.14 and 3.15).

### CODE REVIEW

**Comment by Cyan4973** [comment]
Is it still compatible with `cmake` `v2.8.6` ?

**Comment by dooxe** [comment]
I do not have an environment to test, but the `BUNDLE DESTINATION` option is already present in the cmake 2.8.6 documentation: 
https://cmake.org/cmake/help/v2.8.6/cmake.html#command:install

**Comment by Cyan4973** [comment]
Thanks @dooxe !

**Comment by dooxe** [comment]
My pleasure :)

**Pull request merged**
