### PR TITLE
Add DLLTOOL variable so that one can override dlltool binary

### PR DESCRIPTION
**Pull request by vtorri**
This fixes cross compilation on linux for Windows

### CODE REVIEW

**Comment by Cyan4973** [comment]
Do you want to document this new build macro somewhere in `lib/README.md` ?

**Comment by vtorri** [comment]
that's something to do, indeed. I'll do another pull request for README.md.

**Comment by Cyan4973** [comment]
It seems both the creation of `DLLTOOL` build macro and its documentation would do well in an encompassing PR, since it's the same topic.

Is there a reason you tend to prefer small PR ?

**Comment by vtorri** [comment]
simpler to review and see if there are problems, that's all

**Comment by Cyan4973** [comment]
I agree, small PR are easier to review.
Obviously, it's a balancing act. In this case, I believe the presence of a documentation feels related to the feature itself, and makes more sense bundled together.

**Comment by vtorri** [comment]
that's exactly why i didn't want to write documentation... I will change that and you will still something find to change again and again. I would have prefer you to write this simple doc...

**Comment by vtorri** [comment]
so ? not good enough ?

**Pull request merged**
