### PR TITLE
Enable basic support for riscv64

### PR DESCRIPTION
**Pull request by Hamlin-Li**
Hi,
( I'm new to lz4, please kindly let me know if I need to follow some process for this pr. )
Can you take a look at this simple patch to try to bring basic riscv64 support to lz4?

Thanks!

( github CI support riscv64 is added in https://github.com/lz4/lz4/pull/1299 )

## Test
I have run the test via QEMU by following command:
```
CC=riscv64-linux-gnu-gcc make test
```
There are lots of output, seems there is no error, and the bottom lines of output are:
```
All done, ran 10000 iterations per test.
make[1]: Leaving directory '/home/hamlin/workspace/repos/github/misc/lz4/examples'
```

### CODE REVIEW

**Comment by Cyan4973** [comment]
Thanks for the suggested PR @Hamlin-Li .

A derived important action is to add `risc-v` to our cross-compilation CI test suite,
something which has just been completed and merged into `dev` branch (see https://github.com/lz4/lz4/actions/runs/6579895028/job/17876744032).

Apparently, compilation with `riscv64-linux-gnu-gcc` followed by runtime tests seem work fine out of the box, without any modification (hence without this PR).

Is there anything specifically that your PR unlocks or does better ?

**Comment by t-mat** [comment]
It seems some `gcc` cross compiler for `rv64` doesn't predefine any `riscv64` macro [1].
So, if we need to determine it, we may be able to use `__riscv_xlen` [2], [3].

[1]: https://micro-os-plus.github.io/develop/predefined-macros/
[2]: https://github.com/riscv-non-isa/riscv-toolchain-conventions#cc-preprocessor-definitions
[3]: https://github.com/riscv-non-isa/riscv-c-api-doc/blob/master/riscv-c-api.md#preprocessor-definitions

**Comment by Hamlin-Li** [comment]
@Cyan4973 
Thanks for the work done in https://github.com/lz4/lz4/pull/1299! That’s exactly what I expected.

Just got some silly questions:
1. So with this CI update, will there be a new riscv lib released, and the downstream projects like lz4-java will get it automatically? Or how to let lz4-java to know this new support for riscv?
2. And in the later release, ./NEWS will be updated too?
3. I see some arch related things under ./circleci, do we need to update it with riscv?

At last, just a heads-up, there might be some potential work related to performance refinement for riscv64.

**Comment by Hamlin-Li** [comment]
For your question, `Is there anything specifically that your PR unlocks or does better ?`, I'm not sure if this patch is still necessary.
IMHO, it will affect `__64BIT__`, which affects other things. I'm totally new to lz4's code base, so it's up to you or some other experts in lz4.

**Comment by Hamlin-Li** [comment]
@t-mat Thanks for pointing out and share the information!

**Comment by t-mat** [comment]
I've checked predefined macro definition of `riscv64-linux-gnu-gcc` 11.4.0.  It contains the following `#define`s :

```
#define _LP64 1
#define __LP64__ 1
// ...
#define __SIZEOF_POINTER__ 8
// ...
#define __riscv 1
#define __riscv_xlen 64
```

> Apparently, compilation with riscv64-linux-gnu-gcc followed by runtime tests seem work fine out of the box, without any modification (hence without this PR).

Since `lz4/programs/platform.h` already has `#if` for `__SIZE_OF_POINTER__ == 8`, `_LP64` and `__LP64__`, we can safely compile our code without this PR as @Cyan4973 observed.


> Is there anything specifically that your PR unlocks or does better ?

Although I don't know much about `rv64` configurations, but they may have equivalent of `x32`.  If so, I think this PR may be meaningful for them.

<details><summary>Full predefined macros from `riscv64-linux-gnu-gcc` 11.4.0</summary>

```
$ riscv64-linux-gnu-gcc --version
riscv64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ riscv64-linux-gnu-gcc -march=rv64imafdc_zicsr -mabi=lp64d -mcmodel=medany  -msmall-data-limit=8 -E -dM - < /dev/null | egrep -i 'risc|abi|atomic|float|fp|gcc|gnu|end|diff|lp|size|stdc|version' | sort
#define _LP64 1
#define _STDC_PREDEF_H 1
#define __ATOMIC_ACQUIRE 2
#define __ATOMIC_ACQ_REL 4
#define __ATOMIC_CONSUME 1
#define __ATOMIC_RELAXED 0
#define __ATOMIC_RELEASE 3
#define __ATOMIC_SEQ_CST 5
#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__
#define __FP_FAST_FMA 1
#define __FP_FAST_FMAF 1
#define __FP_FAST_FMAF32 1
#define __FP_FAST_FMAF32x 1
#define __FP_FAST_FMAF64 1
#define __GCC_ATOMIC_BOOL_LOCK_FREE 1
#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 1
#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2
#define __GCC_ATOMIC_CHAR_LOCK_FREE 1
#define __GCC_ATOMIC_INT_LOCK_FREE 2
#define __GCC_ATOMIC_LLONG_LOCK_FREE 2
#define __GCC_ATOMIC_LONG_LOCK_FREE 2
#define __GCC_ATOMIC_POINTER_LOCK_FREE 2
#define __GCC_ATOMIC_SHORT_LOCK_FREE 1
#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1
#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
#define __GCC_IEC_559 2
#define __GCC_IEC_559_COMPLEX 2
#define __GNUC_EXECUTION_CHARSET_NAME "UTF-8"
#define __GNUC_MINOR__ 4
#define __GNUC_PATCHLEVEL__ 0
#define __GNUC_STDC_INLINE__ 1
#define __GNUC_WIDE_EXECUTION_CHARSET_NAME "UTF-32LE"
#define __GNUC__ 11
#define __GXX_ABI_VERSION 1016
#define __LP64__ 1
#define __ORDER_BIG_ENDIAN__ 4321
#define __ORDER_LITTLE_ENDIAN__ 1234
#define __ORDER_PDP_ENDIAN__ 3412
#define __PTRDIFF_MAX__ 0x7fffffffffffffffL
#define __PTRDIFF_TYPE__ long int
#define __PTRDIFF_WIDTH__ 64
#define __SIG_ATOMIC_MAX__ 0x7fffffff
#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)
#define __SIG_ATOMIC_TYPE__ int
#define __SIG_ATOMIC_WIDTH__ 32
#define __SIZEOF_DOUBLE__ 8
#define __SIZEOF_FLOAT__ 4
#define __SIZEOF_INT128__ 16
#define __SIZEOF_INT__ 4
#define __SIZEOF_LONG_DOUBLE__ 16
#define __SIZEOF_LONG_LONG__ 8
#define __SIZEOF_LONG__ 8
#define __SIZEOF_POINTER__ 8
#define __SIZEOF_PTRDIFF_T__ 8
#define __SIZEOF_SHORT__ 2
#define __SIZEOF_SIZE_T__ 8
#define __SIZEOF_WCHAR_T__ 4
#define __SIZEOF_WINT_T__ 4
#define __SIZE_MAX__ 0xffffffffffffffffUL
#define __SIZE_TYPE__ long unsigned int
#define __SIZE_WIDTH__ 64
#define __STDC_HOSTED__ 1
#define __STDC_IEC_559_COMPLEX__ 1
#define __STDC_IEC_559__ 1
#define __STDC_IEC_60559_BFP__ 201404L
#define __STDC_IEC_60559_COMPLEX__ 201404L
#define __STDC_ISO_10646__ 201706L
#define __STDC_UTF_16__ 1
#define __STDC_UTF_32__ 1
#define __STDC_VERSION__ 201710L
#define __STDC__ 1
#define __VERSION__ "11.4.0"
#define __gnu_linux__ 1
#define __riscv 1
#define __riscv_a 2000000
#define __riscv_arch_test 1
#define __riscv_atomic 1
#define __riscv_c 2000000
#define __riscv_cmodel_medany 1
#define __riscv_cmodel_pic 1
#define __riscv_compressed 1
#define __riscv_d 2000000
#define __riscv_div 1
#define __riscv_f 2000000
#define __riscv_fdiv 1
#define __riscv_flen 64
#define __riscv_float_abi_double 1
#define __riscv_fsqrt 1
#define __riscv_i 2000000
#define __riscv_m 2000000
#define __riscv_mul 1
#define __riscv_muldiv 1
#define __riscv_xlen 64
#define __riscv_zicsr 2000000
#define __riscv_zifencei 2000000
```
</details>

**Comment by Cyan4973** [comment]
> ./NEWS will be updated too?

Yes, `NEWS` will mention that `lz4` code base is now tested against risc-v instruction set.
It probably was already working fine, but now, it is also continuously tested, so we can officially announce risc-v support.

> I see some arch related things under ./circleci, do we need to update it with riscv?

No need to duplicate the same test twice. Once on Github CI is fine enough.

As a future extension of this work, we could later extend the `risc-v` tests to check multiple ABIs.

> how to let lz4-java to know this new support for riscv?

I'm not qualified enough to answer this question.
On first look, I don't see why support for `risc-v` would be different from `arm` or `mips` for example.
So I would expect the same method that makes it possible to run `lz4-java` on these cpus to also work for `risc-v`.
But that's a relatively vague statement. I would recommend to direct your questions towards the `lz4-java` project.

> I've checked predefined macro definition

Thanks @t-mat , this was very useful, and the reference provided were great.

I think this patch is in good shape,
at least it seems it doesn't harm,
and there might be scenarios where it might help, when the automatic width detection may not work
(presumably on compilers less complete than modern `gcc` and `clang`).

**Review by Cyan4973 — APPROVED** [review]

**Comment by Hamlin-Li** [comment]
@Cyan4973 @t-mat Thanks for your reviewing and detailed information!

**Pull request merged**
