### PR TITLE
Add basic, failing test for emscripten

### PR DESCRIPTION
**Pull request by jscheid**
See lz4/lz4#397

@Cyan4973 here is a very first iteration on the idea of adding emscripten tests, suitable for testing how lz4 behaves when encode/decode buffers are allocated at low memory locations.

I can run this on my Mac via Homebrew as follows:

```sh
brew install emscripten
export LLVM=/usr/local/Cellar/emscripten/1.37.18/libexec/llvm/bin
export PATH=/usr/local/Cellar/emscripten/1.37.18/libexec/llvm/bin:$PATH
make -C tests test-emscripten
```

You should be able to observe the following:
- The test still fail after applying the first patch from #397 
- Applying the second patch from #397 will make the tests pass
- They will still pass if you increase `MESSAGE_MAX_BYTES` from 1024 to 4096
- However, they will fail again once you switch around `inpBuf` and `decBuf` in
  the `buffers` struct (leaving `MESSAGE_MAX_BYTES` at 4096), suggesting that there is still an issue unaddressed.

Do you think you can take it from here? Let me know if I can be of more help.

### CODE REVIEW

**Comment by Cyan4973** [comment]
That's a pretty good beginning, let's start investigating

**Comment by Cyan4973** [comment]
The part which tries to launch `safari` on my laptop just fails,
but the console section seems to trigger a consistent scenario : 
```
block 0: PASS, decPtr=0xe6c
block 1: PASS, decPtr=0xe6d
block 2: PASS, decPtr=0x10d5
block 3: PASS, decPtr=0x1164
block 4: PASS, decPtr=0x149e
block 5: PASS, decPtr=0x1895
block 6: PASS, decPtr=0x1ac4
block 7: PASS, decPtr=0x1d48
block 8: PASS, decPtr=0x1ece
block 9: PASS, decPtr=0x2279
block 10: PASS, decPtr=0x2490
block 11: PASS, decPtr=0x257e
block 12: PASS, decPtr=0x2846
block 13: PASS, decPtr=0x2bbc
block 14: PASS, decPtr=0x2d95
block 15: PASS, decPtr=0x2e71
block 16: PASS, decPtr=0x31cc
FAIL: 2
```

**Comment by jscheid** [comment]
@Cyan4973 try using chrome:

```sh
make -C tests test-emscripten EMRUN_FLAGS=--browser=chrome
```

I've just pushed a commit that fixes all issues I can find... with this change I can't make it fail anymore, no matter what the message size and which order the buffers appear.

**Comment by Cyan4973** [comment]
There are 2 parts in this PR : 
- The emscripten test : this one is pretty interesting, as it adds a new test case to check, and with a bit of work, could be integrated into the LZ4 CI tests suite
- The fix : I'm sure it works for your use case, but unfortunately, I can see it fail for other use cases, where the force cast to `ptrdiff_t` doesn't end well.

So I guess I would prefer 2 separate issues.
The most promising one is the emscripten test, which is a pre-requisite to investigate a solution for it.

**Comment by jscheid** [comment]
Hi @Cyan4973, sure, that makes sense. After rebasing onto current dev branch I can't get the emscripten tests to pass anymore anyway. New PR at #430

I'll close this one for now. Thanks again for looking into this.

**Pull request closed without merging**
