### PR TITLE
[cmake] Always create lz4 target.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
See facebook/zstd#3965.

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
CI failures are unrelated; the CMake jobs are green.

**Comment by t-mat** [comment]
Sorry for CI issue.  #1416 will fix it.

**Comment by Cyan4973** [comment]
Could you give an example of what was not working before and that works fine now with this PR ?

**Comment by teo-tsirpanis** [comment]
In lz4 installled packages with both a static and shared library built, the unified `lz4::lz4` CMake target is not available. This PR defines it always, allowing developers to reference it with confidence and support both static and dynamic linkage of lz4 in their apps.

I opened this PR to mirror a similar PR to zstd, with the intent to proactively address an issue like facebook/zstd#3859 on lz4.

**Comment by Cyan4973** [comment]
Is there any test we could do in CI that would "prove" the problem (aka fail) and succeed after this PR is applied ?

**Comment by teo-tsirpanis** [comment]
Good idea, I added a check in the CMake tests.

**Review by Cyan4973 — APPROVED** [review]

**Comment by Cyan4973** [comment]
Thanks @teo-tsirpanis !

**Pull request merged**
