### PR TITLE
update -H documentation regarding compression levels

### PR DESCRIPTION
**Pull request by Cyan4973**
answers @t-mat comment in #1504

### CODE REVIEW

**Comment by Cyan4973** [comment]
Visual 2022 tests have been failing recently,
though the reason why is unclear.

**Comment by t-mat** [comment]
Basic analysis of the failure for VS2022 tests
==============

The first failed commit
-----------------------

[PR #1497](https://github.com/lz4/lz4/pull/1497) has the first failed test log.
But since this is a changset for the `lib/Makefile` which is not used by VS2022, obviously this PR/commit is not an actual root cause of the failure.


Which test is failed?
---------------------

It seems it has been failed with the following test:

```
12-LZ4F_decompLZ4F_decompress_followHintress
```


How this test is invoked by GitHub Actions?
-------------------------

- `ci.yaml`
- -> `build/VS2022/build-and-test-win32-release.bat`
- -> `build/VS2022/_test.bat`.
- -> `!BIN!\fullbench.exe --no-prompt -i1 %TEST_FILES%`
- Fail


How can we reproduce this issue locally?
----------------------------------------

The following commands should reproduce this issue (or not).

<details><summary>Actual commands</summary>

```
cmd.exe
cd /d "%PUBLIC%\Documents"
git clone https://github.com/lz4/lz4.git lz4-1506
cd lz4-1506
git branch -v
: * dev e0781fbe Merge pull request #1493 from lz4/dependabot/github_actions/github/codeql-action-3.26.2
git log -1
: commit e0781fbe4b667f529864b268c5df491a9094e3f0 (HEAD -> dev, origin/dev, origin/HEAD)
: Author: Yann Collet <Cyan4973@users.noreply.github.com>
: Date:   Mon Aug 19 09:34:06 2024 -0700
cd .\build\VS2022
.\build-and-test-win32-release.bat
```

</details>


Did I (@t-mat) reproduce this issue locally?
--------------------------------------------

Not exactly same.  But partially, yes.  It's strange.

1. First time: it passes all tests.  But (de)compression speed is really slow

```
LZ4_compress_default:18.0MB/s
LZ4F_decompress:143.9MB/s
LZ4F_decompLZ4F_decompress_followHintress: 138.3MB/s
```

2. Second time: it still running after showing the following test log

```
*** LZ4 speed analyzer v1.10.0 32-bits, by Yann Collet ***
- 1 iterations -
 ..\..\tests\COPYING :
Compression functions :
 1-LZ4_compress_default               :     14901 ->     8589 (57.64%), 1092.2 MB/s
 2-LZ4_compress_default(small dst)    :     14901 ->     8589 (57.64%),  995.1 MB/s
...
11-LZ4F_decompress                    :     14901 ->  2525.3 MB/s
<<< @t-mat : Above is the last line in the terminal.  After 1 hour or so, fullbench.exe (32bit) is still active and running. >>>
```

EDIT: 1 more hour passed, `fullbench.exe` (32bit) is active and comsuming 7% of my CPU time.  It seems its `for(;;)` infinite loop failed to break for some reason.  Abort it for now.

**Comment by t-mat** [comment]
I opened a new issue for this problem: #1507

**Comment by t-mat** [comment]
> First time: it passes all tests. But (de)compression speed is really slow

I realized I've invoked debug build script ( `build/VS2022/build-and-test-win32-debug.bat` ).

**Pull request merged**
