### PR TITLE
Support for 128bit pointers like AS400

### PR DESCRIPTION
**Pull request by Cyan4973**
This answers https://github.com/lz4/lz4/issues/485,
making it possible for `lz4` to compile on systems with 128-bit pointers.

I've taken the less disruptive approach to only increase size constants when pointers are detected as 128-bits (defined as `sizeof(void*)==16`). This way, the API remains unchanged for existing 32-bit and 64-bit systems.

Other possibilities involved increasing the size for all ABIs, or to get rid of the size and force usage of the `struct` definition. They were less preferred, due to risks of potentially breaking some unidentified user applications.

_Note_ : I'm unfortunately unable to test this change, as I don't have any AS400 emulator around (nor cross-compiler), so I've trusted values provided by @JoachimSchneider . Finding a way to test compilation on such target could be an interesting (if complex) follow up.

### CODE REVIEW

**Comment by JoachimSchneider** [comment]
Hello Yann,

i will test these changes on AS400 now and let you know the results.

Thank you,
Joachim Schneider


On Tue, 18 Sep 2018, Yann Collet wrote:

> This answers https://github.com/lz4/lz4/issues/485,
> making it possible for `lz4` to compile on systems with 128-bit pointers.
>
> I've taken the less disruptive approach to only increase size constants when pointers are detected as 128-bits (defined as `sizeof(void*)==16`). This way, the API remains unchanged for existing 32-bit and 64-bit systems.
>
> Other possibilities involved increasing the size for all ABIs, or to get rid of the size and force usage of the `struct` definition. They were less preferred, due to risks of potentially breaking some user application.
>
> _Note_ : I'm unfortunately unable to test this change, as I don't have any AS400 emulator around (nor cross-compiler), so I've trusted values provided by @JoachimSchneider . Finding a way to test compilation on such target could be a good follow up.
> You can view, comment on, or merge this pull request online at:
>
>  https://github.com/lz4/lz4/pull/578
>
> -- Commit Summary --
>
>  * use byU32 mode for any pointer > 32-bit
>  * increase lz4hc context size as constant for 128-bit systems
>  * Merge branch 'dev' into support128bit
>  * increase size of LZ4 contexts for 128-bit systems
>
> -- File Changes --
>
>    M lib/lz4.c (25)
>    M lib/lz4.h (30)
>    M lib/lz4hc.h (40)
>
> -- Patch Links --
>
> https://github.com/lz4/lz4/pull/578.patch
> https://github.com/lz4/lz4/pull/578.diff
>
>

--
%%
% Dr. Joachim Schneider
%
% SAP on IBM i, DB/OS Platforms
% SAP SE, Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany
%
% Tel.: +49/6227/7-68715
% mailto: joachim.schneider@sap.com
%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Pflichtangaben/Mandatory Disclosure Statements:

http://www.sap.com/germany/about/company/legal/impressum_DE.epx

Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige
vertrauliche Informationen enthalten. Sollten Sie diese E-Mail
irrtuemlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts,
eine Vervielfaeltigung oder Weitergabe der E-Mail ausdruecklich
untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die
empfangene E-Mail. Vielen Dank.

This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution
of it is strictly prohibited. Please inform us immediately and destroy
the original transmittal. Thank you for your cooperation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by JoachimSchneider** [comment]
Hello Yann,

i tested your pull request (https://github.com/lz4/lz4/pull/578) on AS/400.

With one additional change in lz4.h it compiles and works:

*********************************************************************************
--- lz4.h       2018/09/20 08:57:50     1.1
+++ lz4.h       2018/09/20 09:07:54
@@ -564,7 +564,7 @@
   *         this definition is not API/ABI safe,
   *         and may change in a future version !
   */
-#define LZ4_STREAMDECODESIZE_U64 (4 + ((sizeof(void*)==16) ? 2 : 0) /*AS-400*/ )
+#define LZ4_STREAMDECODESIZE_U64 (4 + ((sizeof(void*)==16) ? 4 : 0) /*AS-400*/ )
  #define LZ4_STREAMDECODESIZE     (LZ4_STREAMDECODESIZE_U64 * sizeof(unsigned long long))
  union LZ4_streamDecode_u {
      unsigned long long table[LZ4_STREAMDECODESIZE_U64];
*********************************************************************************

Many greetings,
Joachim


On Tue, 18 Sep 2018, Yann Collet wrote:

> This answers https://github.com/lz4/lz4/issues/485,
> making it possible for `lz4` to compile on systems with 128-bit pointers.
>
> I've taken the less disruptive approach to only increase size constants when pointers are detected as 128-bits (defined as `sizeof(void*)==16`). This way, the API remains unchanged for existing 32-bit and 64-bit systems.
>
> Other possibilities involved increasing the size for all ABIs, or to get rid of the size and force usage of the `struct` definition. They were less preferred, due to risks of potentially breaking some user application.
>
> _Note_ : I'm unfortunately unable to test this change, as I don't have any AS400 emulator around (nor cross-compiler), so I've trusted values provided by @JoachimSchneider . Finding a way to test compilation on such target could be a good follow up.
> You can view, comment on, or merge this pull request online at:
>
>  https://github.com/lz4/lz4/pull/578
>
> -- Commit Summary --
>
>  * use byU32 mode for any pointer > 32-bit
>  * increase lz4hc context size as constant for 128-bit systems
>  * Merge branch 'dev' into support128bit
>  * increase size of LZ4 contexts for 128-bit systems
>
> -- File Changes --
>
>    M lib/lz4.c (25)
>    M lib/lz4.h (30)
>    M lib/lz4hc.h (40)
>
> -- Patch Links --
>
> https://github.com/lz4/lz4/pull/578.patch
> https://github.com/lz4/lz4/pull/578.diff
>
>

--
%%
% Dr. Joachim Schneider
%
% SAP on IBM i, DB/OS Platforms
% SAP SE, Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany
%
% Tel.: +49/6227/7-68715
% mailto: joachim.schneider@sap.com
%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Pflichtangaben/Mandatory Disclosure Statements:

http://www.sap.com/germany/about/company/legal/impressum_DE.epx

Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige
vertrauliche Informationen enthalten. Sollten Sie diese E-Mail
irrtuemlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts,
eine Vervielfaeltigung oder Weitergabe der E-Mail ausdruecklich
untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die
empfangene E-Mail. Vielen Dank.

This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution
of it is strictly prohibited. Please inform us immediately and destroy
the original transmittal. Thank you for your cooperation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by Cyan4973** [comment]
Hi @JoachimSchneider 
Thanks for the feedback.
I was initially surprised for the need of more space, since the sized structure only has 2 pointers, hence `+2` should have been enough,
but I then noticed the interleaved nature of structure members (`void*, size_t, void*, size_t`).
This works fine as long as `sizeof(size_t) == sizeof(void*)`, which was the initial assumption,
but creates some padding when these 2 types have different sizes.

We could go in 2 directions : 
- just increase the size, as suggested
- reorder structure members, to avoid padding.

The second option is (slightly) more efficient, which hardly matters since only AS400 is impacted.
On the other hand, it would break code which rely on members order, such as static initialization. This second issue is also highly unlikely, since it's an internal type which is initialized with a `memset(,0,)`.
So both approaches are practical.

Save any preference, I'll experiment with solution 2.

**Comment by JoachimSchneider** [comment]
Hello Yann,

yes you are right, it seems to be an alignement issue: All pointers on the AS/400 must be aligned to 16-byte boundaries. This is demonstrated by this small dem program:

========================================================================

#include <stdio.h>
#include <sys/types.h>


#define TO_STR_(x)    #x
#define TO_STR(x)     TO_STR_(x)
#define PRINT_SIZE(x) ( printf("sizeof(%s) = %2d\n", TO_STR(x), (int)sizeof(x)) )

#define SIZE_T      size_t
#define ULONG_T     unsigned long long
#define PTR_T       void *
#define STRUCT_A_T  struct { void * p0; size_t s0; void * p1; size_t s1; }
#define STRUCT_B_T  struct { void * p0; void * p1; size_t s0; size_t s1; }


int main(int argc, char *argv[])
{
    PRINT_SIZE(SIZE_T);
    PRINT_SIZE(ULONG_T);
    PRINT_SIZE(PTR_T);
    PRINT_SIZE(STRUCT_A_T);
    PRINT_SIZE(STRUCT_B_T);

    return 0;
}

========================================================================

and its output on AS/400:

========================================================================

sizeof(size_t) =  4
sizeof(unsigned long long) =  8
sizeof(void *) = 16
sizeof(struct { void * p0; size_t s0; void * p1; size_t s1; }) = 64
sizeof(struct { void * p0; void * p1; size_t s0; size_t s1; }) = 48

========================================================================

Thank you, many greetings,
Joachim Schneider


On Mon, 24 Sep 2018, Yann Collet wrote:

> Hi @JoachimSchneider
> Thanks for the feedback.
> I was initially surprised for the need of more space, since the sized structure only has 2 pointers, hence `+2` should have been enough,
> but I then noticed the interleaved nature of structure members (`void*, size_t, void*, size_t`).
> This works fine as long as `sizeof(size_t) == sizeof(void*)`, which was the initial assumption,
> but creates some padding when these 2 types have different sizes.
>
> We could go in 2 directions :
> - just increase the size, as suggested
> - reorder structure members, to avoid padding.
>
> The second option is (slightly) more efficient, which hardly matters since only AS400 is impacted.
> On the other hand, it would break code which rely on members order, such as static initialization. This second issue is also highly unlikely, since it's an internal type which is initialized with a `memset(,0,)`.
> So both approaches are practical.
>
> Save any preference, I'll experiment with solution 2.
>
>

--
%%
% Dr. Joachim Schneider
%
% SAP on IBM i, DB/OS Platforms
% SAP SE, Dietmar-Hopp-Allee 16, 69190 Walldorf, Germany
%
% Tel.: +49/6227/7-68715
% mailto: joachim.schneider@sap.com
%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Pflichtangaben/Mandatory Disclosure Statements:

http://www.sap.com/germany/about/company/legal/impressum_DE.epx

Diese E-Mail kann Betriebs- oder Geschäftsgeheimnisse oder sonstige
vertrauliche Informationen enthalten. Sollten Sie diese E-Mail
irrtuemlich erhalten haben, ist Ihnen eine Kenntnisnahme des Inhalts,
eine Vervielfaeltigung oder Weitergabe der E-Mail ausdruecklich
untersagt. Bitte benachrichtigen Sie uns und vernichten Sie die
empfangene E-Mail. Vielen Dank.

This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution
of it is strictly prohibited. Please inform us immediately and destroy
the original transmittal. Thank you for your cooperation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Pull request merged**
