### PR TITLE
Meson updates

### PR DESCRIPTION
**Pull request by tristan957**

### CODE REVIEW

**Comment by tristan957** [comment]
@Cyan4973 would appreciate a merge on this when you get a chance :)

**Comment by tristan957** [comment]
@Cyan4973 @t-mat here are the Meson fixes for freestanding in addition to add a dependency override

**Comment by t-mat** [comment]
@tristan957 Looks good.  Thanks!
Also as an adaptation of your idea, I'll add `test-freestanding` to the `all` of `tests/Makefile`.

**Comment by t-mat** [comment]
Sorry for the test failure.
It seems https://github.com/lz4/lz4/actions/runs/3536624577 has successed but https://github.com/lz4/lz4/actions/runs/3542454122 failed.

Since failed tests are unrelated to Meson and we didn't change our .github/ci.yml, I believe it's my mistake, issue from upstream clang or problem in GH-Actions.

**Comment by tristan957** [comment]
@t-mat do you think rebasing on master or rerunning failed jobs would help?

**Comment by t-mat** [comment]
Since it doesn't seem random error, it unlikely fixed by the re-running the test.

----
It seems this error is caused by the changing default behavior of `clang-12`.

In the our last succeeded test, `clang-12` was trying to search `gcc/*/11/*` 
https://github.com/lz4/lz4/actions/runs/3536624577/jobs/5935832118#step:17:291

But in the error log of last commit of this PR, `clang-12` has failed to find library in `gcc/*/12/*`.
https://github.com/lz4/lz4/actions/runs/3542454122/jobs/5947968452#step:17:293

Therefore, it seems `clang-12` has changed their search path from `lib*32gcc-11-dev` to `lib*32gcc-12-dev` by the unknown reason.


edit : In these two tests, there's no version difference of `clang` and `multilib`.  Anyway, changing version of multilib may fix this issue.

**Comment by tristan957** [comment]
@t-mat while I have you, do you think this PR can be merged?

**Comment by t-mat** [comment]
@tristan957 I think the shape of this PR itself is good.  But since test for this PR has failed, we must fix it to ease reviewing process.

I have to go out for now.  So I'll begin to fix this GitHub Actions issue in 10 to 12 hours later.  Again, I'm really sorry for the inconvenience which is caused by my mistake.

**Comment by tristan957** [comment]
Not a big deal though this PR doesn't touch anything related to the test failure since I only touch meson.build files and the failing jobs use the Makefile based build.

**Comment by Cyan4973** [comment]
Hi @tristan957 

I noticed you pushed an update 1 hour ago,

In your opinion, is this PR completed, or do you still intend to work and update it ?

**Comment by tristan957** [comment]
It is completed. I pushed to consume the CI fix from @t-mat

**Review by Cyan4973 — APPROVED** [review]

**Comment by tristan957** [comment]
@Cyan4973 @t-mat I appreciate your help in this PR :)

**Pull request merged**
