### PR TITLE
Pedantic suggestions

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Pedantic suggestions by [`checkpatch.pl`](https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl) from the Linux kernel.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Thanks for the suggestions @DimitriPapadopoulos ,

one of the things I would like to keep unchanged
is the white space at the end of printed strings, 
typically just before the `\n`.

There are scenarios in which the printed lines overwrite an existing blob of characters,
in which cases, the additional space character is helpful to distinguish the message from the noisy text background.
This is a property I would like to preserve.

**Comment by DimitriPapadopoulos** [comment]
I'll remove the relevant commit. However, I wonder whether all current occurrences of trailing whitespaces have to do with these scenarios, or whether new occurrences of trailing whitespaces should be added to fully cover such scenarios. I mean, are these occurrences fully under control? Don't get me wrong, there's no wrong answer here, I am asking for my own education.

**Comment by DimitriPapadopoulos** [comment]
Fixed by removing that commit.

**Comment by Cyan4973** [comment]
OK,
I would like to come back to this PR, and see if it can be merged.

The main issue here is that it doesn't pass CI tests.
More specifically, it doesn't pass Visual Studio tests in debug mode, which also trigger some additional flags and analyzer pass.

Since the issue is labelled `conditional expression is constant`, it probably doesn't like the `do { ... } while (0)` and other equivalent changes.

I understand the benefits of `do { ... } while (0)` compared to just `{ ... }`,
but this is minor and this code base doesn't expect them.
Meanwhile, Visual Studio compatibility is an important objective in itself.

So I guess passing CI tests (which is mandatory) can be fixed by removing the relevant macro definition changes.

**Comment by t-mat** [comment]
Perhaps, we can introduce inline `__pragma` for msvc.  For example, https://stackoverflow.com/a/4816375

**Comment by DimitriPapadopoulos** [comment]
~~I agree `{ ... }` instead of `do { ... } while (0)` is good enough, especially outside public APIs.~~

**Comment by DimitriPapadopoulos** [comment]
Actually, C4127 has been disabled in most source files:

https://github.com/lz4/lz4/blob/34d9127010f5c0265aad8c13baf718e27d4dd1f1/lib/lz4frame.c#L47-L49

I presume it has been forgotten in a couple files. I'll look into it.

**Comment by DimitriPapadopoulos** [comment]
C4127 is now disabled in all files, and CI tests pass.

**Review by Cyan4973 — APPROVED** [review]

**Pull request merged**
