### PR TITLE
Ensure list test exits with appropiate exit code on failure

### PR DESCRIPTION
**Pull request by gabrielstedman**

### CODE REVIEW

**Comment by gabrielstedman** [comment]
The failure under macOS proves the exit code is now correct and validation fails.

I don't have a macOS environment to troubleshoot and I'm unsure how to gain shell access to that specific github runner.  
I'll try to figure if there's a way to gain local access to this `macos-latest` instance.

**Comment by gabrielstedman** [comment]
I'll close this whilst Investigating a solution

**Comment by Cyan4973** [comment]
Thanks @gabrielstedman !

If I understand properly, there was no issue in the library itself ?
Just the test script needed be updated ?

**Comment by gabrielstedman** [comment]
That's exactly right.

**Pull request closed without merging**
