### PR TITLE
Adapt LZ4_compress_HC_destSize for any input data

### PR DESCRIPTION
**Pull request by remittor**
This PR created for fix issue https://github.com/lz4/lz4/issues/784

### CODE REVIEW

**Comment by remittor** [comment]
Test results **before** fix :

- Fuzzer: **FAIL**
```
$ ./fuzzer
Starting LZ4 fuzzer (64-bits, v1.9.2)
Seed = 4300
Overflow tests : 64 bits mode : no overflow
Test 0 : LZ4_compress_HC_destSize() read src buffer is incorrect ! (seed 0, cycle 0)
```

- fullbench: 19.2 MB/s
```
$ ./fullbench -c10 silesia.tar
*** LZ4 speed analyzer v1.9.2 64-bits, by Yann Collet ***
 silesia.tar :
10-LZ4_compress_HC : 211947520 -> 78002071 (36.80%), 19.2 MB/s
```

Test results **after** fix :

- Fuzzer: **OK**
```
$ ./fuzzer
Starting LZ4 fuzzer (32-bits, v1.9.2)
Seed = 7335
Overflow tests : high address not possible
All unit tests completed successfully compressionLevel=9
  65536 /  65536   - all tests completed successfully
compression ratio: 55.047%
HC compression ratio: 51.917%
ratio with dict: 34.667%
```

- fullbench: 19.2 MB/s
```
$ ./fullbench -c10 silesia.tar
*** LZ4 speed analyzer v1.9.2 64-bits, by Yann Collet ***
 silesia.tar :
10-LZ4_compress_HC : 211947520 -> 78002071 (36.80%), 19.2 MB/s
```

- frametest: **OK** (262144 iterations)
```
$ ./frametest
Starting lz4frame tester (64-bits, 1.9.2)
Seed = 7978
Basic tests completed
All tests completed
```

**Comment by hsiangkao** [comment]
Hi Cyan,

Could you take consider this fix for lz4 upstream?
Otherwise some data could not be compressed effectively...

p.s. I have tested this PR remittor-pr:hc_dstsize_3 with remittor-pr:dev:

before:
(default level 9)
$ ./mkfs.erofs -d9 -zlz4hc enwik9_4k.erofs.compacted.old.img enwik9
-rw-r--r-- 1 hsiangkao hsiangkao  558133248 Mar  5 19:17 enwik9_4k.erofs.compacted.old.img

(best level 12)
$ ./mkfs.erofs -d9 -zlz4hc,12 enwik9_4k.erofs.compacted.new.12.img enwik9
-rw-r--r-- 1 hsiangkao hsiangkao  557142016 Mar  5 19:25 enwik9_4k.erofs.compacted.old.12.img

after:

(default level 9)
$ ./mkfs.erofs.new_hc -d9 -zlz4hc enwik9_4k.erofs.compacted.new.img enwik9
-rw-r--r-- 1 hsiangkao hsiangkao  557998080 Mar  5 19:20 enwik9_4k.erofs.compacted.new.img

(best level 12)
$ ./mkfs.erofs.new_hc -d9 -zlz4hc,12 enwik9_4k.erofs.compacted.new.12.img enwik9
-rw-r--r-- 1 hsiangkao hsiangkao  556982272 Mar  5 19:27 enwik9_4k.erofs.compacted.new.12.img

It seems this PR also optimize compressed size for compressible
data (since for enwik9 all data can be compressed previously as well).

And I have checked the new images can be decompressed
properly as well.

So Tested-by: Gao Xiang <hsiangkao@aol.com>

Thanks,
Gao Xiang

**Comment by Cyan4973** [comment]
Equivalent fix proposed in #923

**Comment by Cyan4973** [comment]
fix merged into `dev`.

I will keep an eye on this one, as it seems it also tackles a few "hacks" that were introduced in order to provide the `_destSize()` variant.

**Comment by remittor** [comment]
Checked this code with real data. Creates too short blocks. Is that bad.

**Pull request closed without merging**
