### PR TITLE
Add aarch64, ppc64le, and s390x to Travis CI for Xenial targets

### PR DESCRIPTION
**Pull request by adamretter**
This PR allows testing on multiple architectures via Travis-CI.

### CODE REVIEW

**Comment by Cyan4973** [comment]
Thanks @adamretter , it's a great add to the test system !

I noticed a few remaining test errors on travis.
I resumed the `ppc64` ones, but they fail the same : 
> An error occurred while generating the build script.

Maybe there is an issue in the .travis file ?

Then, I'm unsure if [this one](https://travis-ci.org/lz4/lz4/jobs/628401861#L44) is revealing of a larger problem.

**Comment by adamretter** [comment]
Regards the:

> An error occurred while generating the build script.

There is so little information that comes back from Travis, it's hard to know what is wrong. We should open a ticket with them I think...

**Comment by adamretter** [comment]
> Then, I'm unsure if this one is revealing of a larger problem.

It looks like maybe ASAN is only supported for ARM64 on Android. Is that how you also interpret the guidance here? - https://github.com/google/sanitizers/wiki/AddressSanitizer#introduction

**Comment by Cyan4973** [comment]
Yes.

It also seems that `ppc64le` support is broken on travisCI since recently.

Maybe we don't need _all_ these tests after all.
Simply remove those that don't pass.

Too long testing time is taking a toll on the developer's feedback loop, so let's not overdo it.

**Comment by adamretter** [comment]
@Cyan4973 did you see something written somewhere about broken ppc64le?

**Comment by Cyan4973** [comment]
Yes, in a thread, on travis support forum.

That being said, the thread concluded with a recent answer stating that the situation is now fixed.
So, `ppc64le` builds should work again.

**Comment by Cyan4973** [comment]
It seems there is a remaining issue with `asan` on `ppc64le` : https://travis-ci.org/lz4/lz4/jobs/633740598#L45

**Comment by adamretter** [comment]
@Cyan4973 Indeed. I am not quite sure where to start with it though... perhaps I should consult the ASAN people?

**Comment by Cyan4973** [comment]
We can probably remove this test, as both `asan` and `ppc64le` are tested separately already.
Maybe just leave a note explaining why this test was removed from the script.

**Comment by adamretter** [comment]
@Cyan4973 I would like to understand why it fails before deciding to remove it ;-)

**Comment by ojeda** [comment]
I would suggest creating an issue for that while adding the rest of the tests to benefit from them in the meantime.

**Comment by Cyan4973** [comment]
It seems this PR was never completed.

I'll try to salvage what I can from it into a feature branch before next release.

**Comment by Cyan4973** [comment]
Superceded by #902

**Pull request closed without merging**
